# Generated by Django 3.0.3 on 2020-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('answer1', models.CharField(blank=True, max_length=10)),
                ('answers2', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
